# Generated by Django 2.2.15 on 2025-03-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_store_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_ads',
        ),
    ]
