# Generated by Django 2.2.15 on 2025-03-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20250303_0908'),
        ('profiles', '0003_remove_profile_total_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_ads',
        ),
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(related_name='saved_by_profiles', through='ads.Bookmark', to='ads.Ads'),
        ),
    ]
