# Generated by Django 2.2.15 on 2025-04-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20250426_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-profile-pic.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
