# Generated by Django 2.2.15 on 2025-06-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20250426_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True, help_text="Seller's reply to the review", null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reply_date',
            field=models.DateTimeField(blank=True, help_text="Date and time of the seller's reply", null=True),
        ),
    ]
