# Generated by Django 2.2.15 on 2025-02-14 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedad',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_ad_items', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ads.Ads'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ads.Conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featuredslot',
            name='current_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot', to='ads.Ads'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='ads.Ads'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.County'),
        ),
        migrations.AddField(
            model_name='adsimages',
            name='ad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.Ads'),
        ),
        migrations.AddField(
            model_name='ads',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='ads.Category'),
        ),
        migrations.AddField(
            model_name='ads',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.City'),
        ),
        migrations.AddField(
            model_name='ads',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='ads.County'),
        ),
        migrations.AddField(
            model_name='ads',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='profiles.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='savedad',
            unique_together={('profile', 'ad')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='ads_message_is_read_a38416_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='ads_message_created_18fc69_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='ads_convers_updated_ee0598_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_time'], name='ads_convers_last_me_69dc81_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['unread_count'], name='ads_convers_unread__cb91d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city_name', 'county')},
        ),
        migrations.AddIndex(
            model_name='ads',
            index=models.Index(fields=['date_created'], name='ads_ads_date_cr_5edad6_idx'),
        ),
        migrations.AddIndex(
            model_name='ads',
            index=models.Index(fields=['category'], name='ads_ads_categor_0bff2a_idx'),
        ),
        migrations.AddIndex(
            model_name='ads',
            index=models.Index(fields=['city'], name='ads_ads_city_id_d9b490_idx'),
        ),
        migrations.AddIndex(
            model_name='ads',
            index=models.Index(fields=['is_featured'], name='ads_ads_is_feat_7c12ed_idx'),
        ),
        migrations.AddIndex(
            model_name='ads',
            index=models.Index(fields=['status'], name='ads_ads_status_a2438d_idx'),
        ),
        migrations.AddIndex(
            model_name='ads',
            index=models.Index(fields=['views_count'], name='ads_ads_views_c_50fe0c_idx'),
        ),
    ]
