# Generated by Django 2.2.15 on 2025-02-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_copy_views_to_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='clicks_count',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='last_clicked',
        ),
    ]
