# Generated by Django 2.2.15 on 2025-03-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_total_ads'),
        ('ads', '0005_auto_20250223_0612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedAd',
            new_name='Bookmark',
        ),
    ]
