# Generated by Django 2.2.15 on 2025-04-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20250423_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='negotiable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not sure')], default='not_sure', max_length=10),
        ),
        migrations.AddField(
            model_name='ads',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
