# Generated by Django 2.2.15 on 2025-04-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_addraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='clothing_size',
            field=models.CharField(blank=True, choices=[('', 'Select Size'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2XL'), ('XXXL', '3XL'), ('CUSTOM', 'Custom Size'), ('NA', 'Not Applicable')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='custom_size',
            field=models.CharField(blank=True, help_text='Specify custom size if selected above', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='shoe_size',
            field=models.CharField(blank=True, choices=[('', 'Select Size'), ('35', 'EU 35 / UK 2.5'), ('36', 'EU 36 / UK 3.5'), ('37', 'EU 37 / UK 4'), ('38', 'EU 38 / UK 5'), ('39', 'EU 39 / UK 6'), ('40', 'EU 40 / UK 6.5'), ('41', 'EU 41 / UK 7.5'), ('42', 'EU 42 / UK 8'), ('43', 'EU 43 / UK 9'), ('44', 'EU 44 / UK 9.5'), ('45', 'EU 45 / UK 10.5'), ('46', 'EU 46 / UK 11'), ('CUSTOM', 'Custom Size')], max_length=10, null=True),
        ),
    ]
