# Generated by Django 2.2.15 on 2025-05-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_auto_20250503_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Likoni', 'Likoni'), ('Kisauni', 'Kisauni'), ('Nyali', 'Nyali'), ('Mtwapa', 'Mtwapa'), ('Lamu', 'Lamu'), ('Mpeketoni', 'Mpeketoni'), ('Faza', 'Faza'), ('Witu', 'Witu'), ('Taita-Taveta', 'Taita-Taveta'), ('Voi', 'Voi'), ('Mwatate', 'Mwatate'), ('Taveta', 'Taveta'), ('Wundanyi', 'Wundanyi'), ('Nairobi', 'Nairobi'), ('Karen', 'Karen'), ("Lang'ata", "Lang'ata"), ('Westlands', 'Westlands'), ('Embakasi', 'Embakasi'), ('Kasarani', 'Kasarani'), ('Kisumu', 'Kisumu'), ('Ahero', 'Ahero'), ('Muhoroni', 'Muhoroni'), ('Homa Bay', 'Homa Bay'), ('Kendu Bay', 'Kendu Bay'), ('Mbita', 'Mbita'), ('Oyugis', 'Oyugis'), ('Migori', 'Migori'), ('Rongo', 'Rongo'), ('Awendo', 'Awendo'), ('Uriri', 'Uriri'), ('Siaya', 'Siaya'), ('Bondo', 'Bondo'), ('Ugunja', 'Ugunja'), ('Yala', 'Yala'), ('Nakuru', 'Nakuru'), ('Naivasha', 'Naivasha'), ('Gilgil', 'Gilgil'), ('Molo', 'Molo'), ('Njoro', 'Njoro'), ('Uasin Gishu', 'Uasin Gishu'), ('Kesses', 'Kesses'), ('Moiben', 'Moiben'), ('Burnt Forest', 'Burnt Forest'), ('Ziwa', 'Ziwa'), ('Turkana', 'Turkana'), ('Kakuma', 'Kakuma'), ('Lokichogio', 'Lokichogio'), ('Kalokol', 'Kalokol'), ('Lokichar', 'Lokichar'), ('West Pokot', 'West Pokot'), ('Kacheliba', 'West Pokot'), ('Alale', 'Alale'), ('Sigor', 'Sigor'), ('Lomut', 'Lomut'), ('Baringo', 'Baringo'), ('Marigat', 'Marigat'), ('Kabarnet', 'Kabarnet'), ('Mogotio', 'Mogotio'), ('Eldama Ravine', 'Eldama Ravine'), ('Bomet', 'Bomet'), ('Longisa', 'Longisa'), ('Sotik', 'Sotik'), ('Chepalungu', 'Chepalungu'), ('Kericho', 'Kericho'), ('Litein', 'Kericho'), ('Bureti', 'Bureti'), ('Sosiot', 'Sosiot'), ('Samburu', 'Samburu'), ('Baragoi', 'Samburu'), ("Archer's Post", "Archer's Post"), ('Wamba', 'Wamba'), ('Kakamega', 'Kakamega'), ('Mumias', 'Mumias'), ('Malava', 'Malava'), ('Butere', 'Butere'), ('Khayega', 'Khayega'), ('Bungoma', 'Bungoma'), ('Webuye', 'Webuye'), ('Malakisi', 'Malakisi'), ('Chwele', 'Chwele'), ('Naitiri', 'Naitiri'), ('Busia', 'Busia'), ('Malaba', 'Malaba'), ('Nambale', 'Nambale'), ('Funyula', 'Funyula'), ('Vihiga', 'Vihiga'), ('Mbale', 'Mbale'), ('Luanda', 'Luanda'), ('Majengo', 'Majengo'), ('Embu', 'Embu'), ('Runyenjes', 'Runyenjes'), ('Siakago', 'Siakago'), ('Manyatta', 'Manyatta'), ('Kitui', 'Kitui'), ('Mwingi', 'Kitui'), ('Mutomo', 'Kitui'), ('Kwa Vonza', 'Kwa Vonza'), ('Machakos', 'Machakos'), ('Athi River', 'Athi River'), ('Mwala', 'Mwala'), ('Kathiani', 'Kathiani'), ('Makueni', 'Makueni'), ('Makindu', 'Makueni'), ('Sultan Hamud', 'Makueni'), ('Kibwezi', 'Makueni'), ('Meru', 'Meru'), ('Maua', 'Meru'), ('Nkubu', 'Meru'), ('Timau', 'Meru'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Marimanti', 'Marimanti'), ('Gatunga', 'Gatunga'), ('Magutuni', 'Magutuni'), ('Garissa', 'Garissa'), ('Dadaab', 'Dadaab'), ('Fafi', 'Fafi'), ('Liboi', 'Liboi'), ('Isiolo', 'Isiolo'), ('Garba Tulla', 'Garba Tulla'), ('Merti', 'Merti'), ('Kinna', 'Kinna'), ('Mandera', 'Mandera'), ('El Wak', 'El Wak'), ('Takaba', 'Takaba'), ('Rhamu', 'Rhamu'), ('Marsabit', 'Marsabit'), ('Laisamis', 'Marsabit'), ('Loiyangalani', 'Loiyangalani'), ('Maikona', 'Maikona'), ('Wajir', 'Wajir'), ('Habaswein', 'Habaswein'), ('Tarbaj', 'Tarbaj'), ('Griftu', 'Griftu'), ('Kiambu', 'Kiambu'), ('Thika', 'Thika'), ('Ruiru', 'Ruiru'), ('Kikuyu', 'Kikuyu'), ('Muranga', 'Muranga'), ('Kenol', 'Kenol'), ('Maragua', 'Maragua'), ('Kangema', 'Kangema'), ('Kirinyaga', 'Kirinyaga'), ('Kerugoya', 'Kerugoya'), ('Sagana', 'Sagana'), ('Wanguru', 'Wanguru'), ('Baricho', 'Baricho'), ('Nyandarua', 'Nyandarua'), ('Ol Kalou', 'Ol Kalou'), ('Ndaragwa', 'Ndaragwa'), ('Njabini', 'Njabini'), ('Engineer', 'Engineer'), ('Nyeri', 'Nyeri'), ('Karatina', 'Karatina'), ('Othaya', 'Othaya'), ('Mweiga', 'Mweiga'), ('Laikipia', 'Laikipia'), ('Nanyuki', 'Laikipia'), ('Rumuruti', 'Laikipia'), ('Nyahururu', 'Laikipia'), ('Dol Dol', 'Dol Dol')], max_length=100),
        ),
    ]
