# Generated by Django 2.2.15 on 2025-05-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0021_auto_20250523_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class (e.g. fa-car, fa-home)', max_length=50, null=True),
        ),
    ]
