# Generated by Django 2.2.15 on 2025-05-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0022_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='categories/')),
                ('item_count', models.IntegerField(default=0)),
                ('bg_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Popular Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TodayDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='deals/')),
                ('discount', models.CharField(max_length=20)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_count', models.IntegerField(default=0)),
                ('is_hot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
