# Generated by Django 2.2.15 on 2025-05-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0023_popularcategory_todaydeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
