# Generated by Django 2.2.15 on 2025-05-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0024_popularcategory_slug'),
    ]

    operations = [
    ]
