# Generated by Django 2.2.15 on 2025-05-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0025_populate_category_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
