# Generated by Django 2.2.15 on 2025-05-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0026_auto_20250529_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='is_bundle',
            field=models.BooleanField(default=False, help_text='Whether this is a bundle deal (multiple items sold together)'),
        ),
    ]
