# Generated by Django 2.2.15 on 2025-06-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0028_auto_20250611_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='ads.Ads'),
        ),
    ]
