# Generated by Django 2.2.15 on 2025-06-17 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0029_auto_20250617_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ads.Ads'),
        ),
    ]
